import { Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

// Responsive sizing helper functions
const isSmallDevice = width < 375;
const isTablet = width >= 768;
const scale = Math.min(width / 375, height / 812); // Base scale on iPhone X dimensions

const size = {
  tiny: Math.round(8 * scale),
  small: Math.round(12 * scale),
  medium: Math.round(16 * scale),
  large: Math.round(20 * scale),
  xlarge: Math.round(24 * scale),
  xxlarge: Math.round(32 * scale),
};

const fontSize = {
  tiny: Math.round(12 * scale),
  small: Math.round(14 * scale),
  medium: Math.round(16 * scale),
  large: Math.round(20 * scale),
  xlarge: Math.round(24 * scale),
  xxlarge: Math.round(34 * scale),
};

export const lightTheme = {
  colors: {
    background: '#F8F9FE',
    surface: 'rgba(255, 255, 255, 0.95)',
    text: '#1A1B1E',
    textSecondary: '#4A4B4F',
    primary: '#4361EE',
    secondary: '#3F37C9',
    accent: '#4895EF',
    border: '#E0E3E7',
    historyItem: '#F1F3F9',
    historyText: '#2B2C2F',
    cardBackground: 'rgba(255, 255, 255, 0.98)',
    error: '#EF476F',
    success: '#06D6A0',
    warning: '#FFD166',
    systemGray: '#95A5A6',
    systemGray2: '#BDC3C7',
    systemGray3: '#DAE1E7',
    gradient: ['#4361EE', '#4895EF'],
  }
};

export const darkTheme = {
  colors: {
    background: '#0A0B0E',
    surface: 'rgba(26, 27, 30, 0.95)',
    text: '#F8F9FE',
    textSecondary: '#A0A4AD',
    primary: '#4361EE',
    secondary: '#3F37C9',
    accent: '#4895EF',
    border: '#2A2B2F',
    historyItem: '#1F2024',
    historyText: '#E0E3E7',
    cardBackground: 'rgba(26, 27, 30, 0.98)',
    error: '#EF476F',
    success: '#06D6A0',
    warning: '#FFD166',
    systemGray: '#95A5A6',
    systemGray2: '#7F8C8D',
    systemGray3: '#636E72',
    gradient: ['#1A1B1E', '#2A2B2F'],
  }
};

export const createStyles = (theme) => ({
  mainContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
    backgroundColor: theme.colors.background,
  },
  container: {
    flex: 1,
    width: '100%',
    height: '100%',
    backgroundColor: 'transparent',
    ...(Platform.OS === 'web' ? {
      maxWidth: isTablet ? 800 : 600,
      alignSelf: 'center',
      marginHorizontal: 'auto',
    } : {}),
  },
  content: {
    flex: 1,
    width: '100%',
    height: '100%',
    position: 'relative',
    zIndex: 1,
  },
  gradientBackground: {
    flex: 1,
    paddingTop: Platform.OS === 'ios' ? size.xlarge : size.small,
  },
  searchContainer: {
    flexDirection: 'row',
    padding: size.medium,
    gap: size.small,
    backgroundColor: theme.colors.surface,
    borderRadius: size.large,
    margin: size.medium,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  input: {
    flex: 1,
    height: 40,
    borderWidth: 0,
    borderRadius: size.small,
    paddingHorizontal: size.medium,
    backgroundColor: theme.colors.background,
    color: theme.colors.text,
    fontSize: fontSize.medium,
    fontWeight: '500',
  },
  button: {
    padding: size.small,
    backgroundColor: theme.colors.primary,
    borderRadius: size.large,
    justifyContent: 'center',
    alignItems: 'center',
    width: 40,
    height: 40,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonText: {
    color: 'white',
    fontSize: fontSize.medium,
    fontWeight: '600',
  },
  historyContainer: {
    padding: size.medium,
    marginBottom: size.small,
    maxWidth: '100%',
  },
  historyItem: {
    backgroundColor: theme.colors.historyItem,
    paddingHorizontal: size.medium,
    paddingVertical: size.small,
    borderRadius: 24,
    marginRight: size.small,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  historyText: {
    color: theme.colors.historyText,
    fontSize: fontSize.small,
    fontWeight: '500',
  },
  clearHistoryButton: {
    marginTop: 12,
    padding: 8,
    borderRadius: 16,
    backgroundColor: theme.colors.surface,
  },
  clearHistory: {
    color: theme.colors.primary,
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '600',
    opacity: 0.8,
  },
  weatherContainer: {
    flex: 1,
    padding: size.medium,
  },
  currentWeather: {
    alignItems: 'center',
    marginBottom: size.xlarge,
    backgroundColor: theme.colors.cardBackground,
    padding: size.xlarge,
    borderRadius: 28,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    width: '100%',
    maxWidth: isTablet ? 600 : undefined,
    alignSelf: 'center',
  },
  cityName: {
    fontSize: fontSize.xxlarge,
    fontWeight: '700',
    marginBottom: size.small,
    color: theme.colors.text,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  temperature: {
    fontSize: isSmallDevice ? fontSize.xxlarge * 2 : fontSize.xxlarge * 2.5,
    fontWeight: '200',
    marginBottom: size.small,
    color: theme.colors.text,
    lineHeight: isSmallDevice ? fontSize.xxlarge * 2 : fontSize.xxlarge * 2.5,
    letterSpacing: -2,
  },
  description: {
    fontSize: fontSize.large,
    marginBottom: size.medium,
    textTransform: 'capitalize',
    color: theme.colors.text,
    fontWeight: '500',
    letterSpacing: -0.5,
    textAlign: 'center',
  },
  detailsContainer: {
    flexDirection: isSmallDevice ? 'column' : 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: size.large,
    gap: size.medium,
  },
  detailItem: {
    flex: isSmallDevice ? undefined : 1,
    minWidth: isSmallDevice ? '100%' : 120,
  },
  detailGradient: {
    alignItems: 'center',
    backgroundColor: theme.colors.historyItem,
    padding: size.medium,
    borderRadius: size.large,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  detailIcon: {
    marginBottom: size.small,
    color: theme.colors.primary,
  },
  detailLabel: {
    fontSize: fontSize.small,
    color: theme.colors.textSecondary,
    marginBottom: 4,
    fontWeight: '500',
  },
  detailValue: {
    fontSize: fontSize.medium,
    fontWeight: '600',
    color: theme.colors.text,
  },
  forecast: {
    marginTop: size.xlarge,
    backgroundColor: theme.colors.cardBackground,
    padding: size.xlarge,
    borderRadius: 28,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    width: '100%',
    maxWidth: isTablet ? 600 : undefined,
    alignSelf: 'center',
  },
  forecastTitle: {
    fontSize: fontSize.xlarge,
    fontWeight: '700',
    marginBottom: size.large,
    color: theme.colors.text,
    letterSpacing: -0.5,
  },
  forecastItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: size.medium,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    flexWrap: 'wrap',
  },
  forecastDay: {
    fontSize: fontSize.medium,
    fontWeight: '600',
    color: theme.colors.text,
    width: isSmallDevice ? '100%' : 80,
    letterSpacing: -0.5,
    marginBottom: isSmallDevice ? size.tiny : 0,
  },
  forecastIconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: isSmallDevice ? undefined : 1,
    justifyContent: 'center',
    gap: size.small,
    width: isSmallDevice ? '100%' : undefined,
    marginBottom: isSmallDevice ? size.tiny : 0,
  },
  forecastIconGradient: {
    padding: size.small,
    borderRadius: size.medium,
  },
  forecastTemp: {
    fontSize: fontSize.medium,
    color: theme.colors.text,
    fontWeight: '500',
    textAlign: isSmallDevice ? 'center' : undefined,
  },
  forecastDescription: {
    fontSize: fontSize.small,
    flex: isSmallDevice ? undefined : 1,
    textAlign: isSmallDevice ? 'center' : 'right',
    color: theme.colors.textSecondary,
    fontWeight: '500',
    width: isSmallDevice ? '100%' : undefined,
  },
  placeholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: size.xxlarge,
  },
  placeholderIconContainer: {
    padding: size.xlarge,
    borderRadius: 40,
    marginBottom: size.medium,
  },
  placeholderText: {
    fontSize: fontSize.medium,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    marginTop: size.medium,
    lineHeight: fontSize.large * 1.2,
    fontWeight: '500',
    maxWidth: 300,
  },
  suggestionsContainer: {
    position: 'absolute',
    top: 76,
    left: 16,
    right: 16,
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    zIndex: 1000,
    maxHeight: 300,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  suggestionItem: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  suggestionText: {
    fontSize: 16,
    color: theme.colors.text,
    fontWeight: '500',
  },
  themeToggle: {
    padding: 8,
    backgroundColor: theme.colors.primary,
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  weatherIconContainer: {
    marginBottom: 20,
  },
  iconGradient: {
    padding: 20,
    borderRadius: 30,
  },
  shimmerCity: {
    width: width * 0.6,
    height: 40,
    borderRadius: 20,
    marginBottom: 20,
  },
  shimmerTemp: {
    width: width * 0.4,
    height: 96,
    borderRadius: 20,
    marginBottom: 16,
  },
  shimmerDesc: {
    width: width * 0.5,
    height: 24,
    borderRadius: 12,
    marginBottom: 20,
  },
  shimmerForecastTitle: {
    width: width * 0.4,
    height: 30,
    borderRadius: 15,
    marginBottom: 20,
  },
  shimmerForecastItem: {
    width: '100%',
    height: 60,
    borderRadius: 12,
    marginBottom: 12,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: size.large,
  },
  loadingContent: {
    backgroundColor: theme.colors.cardBackground,
    padding: size.xxlarge,
    borderRadius: size.large,
    alignItems: 'center',
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    width: '90%',
    maxWidth: 400,
  },
  loadingText: {
    marginTop: size.medium,
    fontSize: fontSize.medium,
    color: theme.colors.text,
    fontWeight: '500',
  },
}); 